### ISSUE TITLE
Is this for individuals credit scoring? or for companies/organizations?

### ISSUE THREAD

**Issue by mike-2020** [colfeng/CALM#2]
Is this for individuals credit scoring? or for companies/organizations?

**Comment by colfeng** [comment]
Thank you for your email. Currently, we have multiple tasks that cover both individual credit scoring and credit scoring for companies/organizations. Credit scoring, fraud detection, and claim analysis are tasks related to individuals, whereas financial distress identification is a task related to companies.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "colfeng/CALM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 下午2:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[colfeng/CALM] Is this for individuals credit scoring? or for companies/organizations? (Issue #2)





 
Is this for individuals credit scoring? or for companies/organizations?
