### ISSUE TITLE
Could you please provide the training code?

### ISSUE THREAD

**Issue by jiahuiLeee** [colfeng/CALM#3]
Could you please provide the training code? 
or tell me how to input the training data...

**Comment by colfeng** [comment]
> Could you please provide the training code? or tell me how to input the training data...

https://github.com/Dai-shen/CALM-train

**Comment by jiahuiLeee** [comment]
> > Could you please provide the training code? or tell me how to input the training data...
> 
> https://github.com/Dai-shen/CALM-train

Thanks a lot!!!
